{% set name = "moffragmentor" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moffragmentor-{{ version }}.tar.gz
  sha256: c071b9090b11239ac7d4a3151f3d16e09386ccf9677b946b9c4a0f0ec7ebacda

build:
  entry_points:
    - run_harvest = moffragmentor.cli:run_harvest
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pymatgen
    - click
    - backports.cached-property
    - networkx
    - pyyaml
    - timeout-decorator
    - joblib
    - loguru
    - ase
    - nglview
    - rdkit
    - scikit-spatial
    - pubchempy
    - more-itertools
    - structuregraph-helpers
    - rdkit

test:
  imports:
    - moffragmentor
  commands:
    - run_harvest --help

about:
  home: https://github.com/kjappelbaum/moffragmentor
  summary: Splits MOFs into metal nodes and linkers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kjappelbaum
